"""Buchmann–Kessler–Pohst reduction of certified approximate generators.

Implements the augmented-matrix construction in Lemma 23.4 twice, as in
Theorem 23.5. Zero rows and independence are checked again using enclosures.
"""

from dataclasses import dataclass
from sage.all import QQ,ZZ,AA,RealBallField,matrix,identity_matrix,vector
from .numerics import rational,endpoints,nearest,dyadic_lower
from .runtime import Limits,ResourceLimit
from .lattice import proved_integer_lll


def kessler_lower_bound(context,limits=Limits()):
    return dyadic_lower(lambda R: 1/(1000*R(context.n).sqrt()*R(context.n).log()**3),limits)


def _floor_log2(q):
    q=QQ(q)
    k=int(q.numerator().nbits()-q.denominator().nbits())
    if QQ(2)**k>q:
        k-=1
    return k


def _row_norm_upper_squared(row):
    out=QQ(0)
    for x in row:
        lo,hi=endpoints(x)
        out+=max(abs(lo),abs(hi))**2
    return out


@dataclass(frozen=True)
class BKPResult:
    transform: object
    basis: object
    rank: int
    precision: int
    zero_relations: object
    minimum_lower_bound: object
    report: dict


def _bkp_pass(oracle,mu,rank_bound,integer_columns,limits):
    initial=oracle(64)
    original_k,d=initial.nrows(),initial.ncols()
    n2=d-integer_columns
    if n2<1:
        raise ValueError("BKP expects at least one real coordinate")
    if original_k==0:
        return BKPResult(matrix(ZZ,0,0),initial,0,64,matrix(ZZ,0,0),mu,{})
    k=max(original_k,n2)
    r0=min(int(rank_bound),original_k,d)
    if r0<1:
        raise ValueError("a positive rank upper bound is required for nonempty input")
    A=max(ZZ(1),max(ZZ(AA(_row_norm_upper_squared(row)).sqrt().ceil()) for row in initial.rows()))
    C=QQ(2)**(4*k)*(r0*A/mu)**(r0+1)
    lam=QQ(2)**k*(r0*A/mu)**r0
    T=QQ(2)**(3*k)/mu*(r0*A/mu)**r0
    q=_floor_log2(T)
    threshold_squared=QQ(2)**(k-1)*lam**2
    precision=64
    while precision<=limits.precision:
        balls=oracle(precision)
        if balls.nrows()!=original_k or balls.ncols()!=d:
            raise ValueError("approximation oracle changed its dimensions")
        mids=matrix(QQ,k,d)
        sufficient=True
        for i in range(original_k):
            errors=[]
            for j in range(d):
                lo,hi=endpoints(balls[i,j])
                if j<integer_columns:
                    if lo.ceil()!=hi.floor():
                        sufficient=False;break
                    mids[i,j]=lo.ceil()
                else:
                    mids[i,j]=balls[i,j].mid().exact_rational()
                errors.append(max(abs(lo-mids[i,j]),abs(hi-mids[i,j])))
            if not sufficient or sum(x*x for x in errors)>=(mu/(4*C))**2:
                sufficient=False;break
        if not sufficient:
            precision*=2;continue
        rounded=matrix(ZZ,k,d,lambda i,j:nearest(QQ(2)**(q+1)*mids[i,j]))
        augmented=(2*identity_matrix(ZZ,k)).augment(rounded)
        reduced,U,backend=proved_integer_lll(augmented)
        if abs(U.det())!=1 or U*augmented!=reduced:
            raise ArithmeticError("LLL failed its exact unimodular transformation check")
        zero,nonzero=[],[]
        for i in range(k):
            tail=reduced.row(i)[k:]
            (zero if sum(x*x for x in tail)<=4*threshold_squared else nonzero).append(i)
        zero_transform=U.matrix_from_rows(zero).matrix_from_columns(range(original_k))
        transform=U.matrix_from_rows(nonzero).matrix_from_columns(range(original_k))
        if transform.nrows()>r0:
            raise ArithmeticError("BKP output exceeds the supplied rank bound")
        zeros=zero_transform*balls
        if any(_row_norm_upper_squared(row)>=mu**2 for row in zeros.rows()):
            precision*=2;continue
        basis=transform*balls
        if basis.nrows():
            gram=basis*basis.transpose()
            determinant=gram.det()
            if not determinant>0:
                precision*=2;continue
        return BKPResult(transform,basis,transform.nrows(),precision,zero_transform,mu,{
            'augmented_rows':k,'scaling_exponent':q,'zero_rows_certified':True,
            'independence_certified':True,'input_error_bound':str(mu/(4*C)),
            'LLL_backend':backend,
        })
    raise ResourceLimit("BKP precision budget exhausted")


def bkp_basis(oracle,minimum_lower_bound,rank_bound,integer_columns=0,limits=Limits()):
    """Return an integer basis transformation for the lattice generated by oracle.

    oracle(precision) must enclose the SAME exact generating matrix at every
    precision, with integer coordinates first. Its rows must generate a discrete
    lattice with lambda_1 >= minimum_lower_bound (a caller hypothesis).
    """
    mu=min(QQ(1),rational(minimum_lower_bound))
    if mu<=0 or integer_columns<0:
        raise ValueError("a positive minimum bound and nonnegative integer dimension are required")
    first=_bkp_pass(oracle,mu,rank_bound,integer_columns,limits)
    if not first.rank:
        return first
    M=first.transform
    second=_bkp_pass(lambda p:M*oracle(p),mu,first.rank,integer_columns,limits)
    if second.rank!=first.rank:
        raise ArithmeticError("the second BKP pass changed the certified rank")
    N=second.transform*M
    precision=max(first.precision,second.precision)
    return BKPResult(N,N*oracle(precision),first.rank,precision,first.zero_relations,mu,{
        'algorithm':'Theorem 23.5 (two augmented LLL passes)',
        'first_pass':first.report,'second_pass':second.report,
        'rank_and_integer_span_certified':True,
    })


def gram_volume(oracle,limits=Limits(),start_precision=64):
    """Enclose the Euclidean covolume of a known full row-rank basis."""
    p=start_precision
    while p<=limits.precision:
        B=oracle(p)
        if not B.nrows():
            return QQ(1),QQ(1),p
        determinant=(B*B.transpose()).det()
        if determinant>0:
            lo,hi=endpoints(determinant.sqrt())
            if lo>0 and hi/lo<QQ(101)/100:
                return lo,hi,p
        p*=2
    raise ResourceLimit("covolume approximation did not separate zero within the precision budget")
